export const receptionID = 2000000553

export const patientTitles = [
  {
    label: "   ",
    code: 0
  },
  {
    label: "Mr.",
    code: 1
  },
  {
    label: "Mrs.",
    code: 2
  },
  {
    label: "Ms.",
    code: 3
  },
  {
    label: "Miss",
    code: 4
  },
  {
    label: "Mast.",
    code: 5
  }
]

export const patientSexCodes = [
  {
    label: "   ",
    code: 0
  },
  {
    label: "Female",
    code: 1
  },
  {
    label: "Male",
    code: 2
  },
  {
    label: "Other",
    code: 3
  }
]

export const dVACodes = [
  {
    label: " ",
    code: 0
  },
  {
    label: "Gold",
    code: 1
  },
  {
    label: "White",
    code: 2
  },
  {
    label: "Orange ",
    code: 4
  }
]

export const pensionCodes = [
  {
    label: " ",
    code: 0
  },
  {
    label: "Pensioner Concession Card",
    code: 1
  },
  {
    label: "Health Care Card",
    code: 3
  },
  {
    label: "Commonwealth Seniors Health Card",
    code: 4
  }
]

export const ethnicCodes = [
  { ethnicCode: 0, ethnicType: '' } ,
  { ethnicCode: 1, ethnicType: 'Aboriginal' } ,
  { ethnicCode: 2, ethnicType: 'Torres Strait Islander' } ,
  { ethnicCode: 3, ethnicType: 'Aboriginal/Torres Strait Islander' } ,
  {
    ethnicCode: 999,
    ethnicType: 'Non Aboriginal/Torres Strait Islander'
  } ,
  { ethnicCode: 1000, ethnicType: 'Acehnese' } ,
  { ethnicCode: 1001, ethnicType: 'Afghan' } ,
  { ethnicCode: 1002, ethnicType: 'African American' } ,
  { ethnicCode: 1003, ethnicType: 'Afrikaner' } ,
  { ethnicCode: 1004, ethnicType: 'Akan' } ,
  { ethnicCode: 1005, ethnicType: 'American' } ,
  { ethnicCode: 1006, ethnicType: 'Amhara' } ,
  { ethnicCode: 1007, ethnicType: 'Anglo-Burmese' } ,
  { ethnicCode: 1008, ethnicType: 'Anglo-Indian' } ,
  { ethnicCode: 1009, ethnicType: 'Angolan' } ,
  { ethnicCode: 1010, ethnicType: 'Argentinian' } ,
  { ethnicCode: 1011, ethnicType: 'Armenian' } ,
  { ethnicCode: 1012, ethnicType: 'Assyrian' } ,
  { ethnicCode: 1013, ethnicType: 'Australian' } ,
  { ethnicCode: 1014, ethnicType: 'Austrian' } ,
  { ethnicCode: 1015, ethnicType: 'Azeri' } ,
  { ethnicCode: 1016, ethnicType: 'Balinese' } ,
  { ethnicCode: 1017, ethnicType: 'Barbadian' } ,
  { ethnicCode: 1018, ethnicType: 'Basque' } ,
  { ethnicCode: 1019, ethnicType: 'Batswana' } ,
  { ethnicCode: 1020, ethnicType: 'Belarusan' } ,
  { ethnicCode: 1021, ethnicType: 'Belgian' } ,
  { ethnicCode: 1022, ethnicType: 'Bengali' } ,
  { ethnicCode: 1023, ethnicType: 'Berber' } ,
  { ethnicCode: 1024, ethnicType: 'Bermudan' } ,
  { ethnicCode: 1025, ethnicType: 'Bolivian' } ,
  { ethnicCode: 1026, ethnicType: 'Bosnian' } ,
  { ethnicCode: 1027, ethnicType: 'Brazilian' } ,
  { ethnicCode: 1028, ethnicType: 'Bruneian' } ,
  { ethnicCode: 1029, ethnicType: 'Bulgarian' } ,
  { ethnicCode: 1030, ethnicType: 'Burgher' } ,
  { ethnicCode: 1031, ethnicType: 'Burmese' } ,
  { ethnicCode: 1032, ethnicType: 'Canadian' } ,
  { ethnicCode: 1033, ethnicType: 'Catalan' } ,
  { ethnicCode: 1034, ethnicType: 'Channel Islander' } ,
  { ethnicCode: 1035, ethnicType: 'Chilean' } ,
  { ethnicCode: 1036, ethnicType: 'Chinese' } ,
  { ethnicCode: 1037, ethnicType: 'Colombian' } ,
  { ethnicCode: 1038, ethnicType: 'Cook Islander' } ,
  { ethnicCode: 1039, ethnicType: 'Coptic' } ,
  { ethnicCode: 1040, ethnicType: 'Costa Rican' } ,
  { ethnicCode: 1041, ethnicType: 'Croatian' } ,
  { ethnicCode: 1042, ethnicType: 'Cuban' } ,
  { ethnicCode: 1043, ethnicType: 'Cypriot' } ,
  { ethnicCode: 1044, ethnicType: 'Czech' } ,
  { ethnicCode: 1045, ethnicType: 'Danish' } ,
  { ethnicCode: 1046, ethnicType: 'Dinka' } ,
  { ethnicCode: 1047, ethnicType: 'Dutch' } ,
  { ethnicCode: 1048, ethnicType: 'Ecuadorian' } ,
  { ethnicCode: 1049, ethnicType: 'Egyptian' } ,
  { ethnicCode: 1050, ethnicType: 'English' } ,
  { ethnicCode: 1051, ethnicType: 'Eritrean' } ,
  { ethnicCode: 1052, ethnicType: 'Estonian' } ,
  { ethnicCode: 1053, ethnicType: 'Ethiopian' } ,
  { ethnicCode: 1054, ethnicType: 'Fijian' } ,
  { ethnicCode: 1055, ethnicType: 'Filipino' } ,
  { ethnicCode: 1056, ethnicType: 'Finnish' } ,
  { ethnicCode: 1057, ethnicType: 'Flemish' } ,
  { ethnicCode: 1058, ethnicType: 'French' } ,
  { ethnicCode: 1059, ethnicType: 'French Canadian' } ,
  { ethnicCode: 1060, ethnicType: 'Frisian' } ,
  { ethnicCode: 1061, ethnicType: 'Georgian' } ,
  { ethnicCode: 1062, ethnicType: 'German' } ,
  { ethnicCode: 1063, ethnicType: 'Ghanaian' } ,
  { ethnicCode: 1064, ethnicType: 'Gibraltarian' } ,
  { ethnicCode: 1065, ethnicType: 'Greek' } ,
  { ethnicCode: 1066, ethnicType: 'Guatemalan' } ,
  { ethnicCode: 1067, ethnicType: 'Gujarati' } ,
  { ethnicCode: 1068, ethnicType: 'Guyanese' } ,
  { ethnicCode: 1069, ethnicType: 'Hawaiian' } ,
  { ethnicCode: 1070, ethnicType: 'Hazara' } ,
  { ethnicCode: 1071, ethnicType: 'Hispanic' } ,
  { ethnicCode: 1072, ethnicType: 'Hmong' } ,
  { ethnicCode: 1073, ethnicType: 'Hungarian' } ,
  { ethnicCode: 1074, ethnicType: 'Hutu' } ,
  { ethnicCode: 1075, ethnicType: 'Icelandic' } ,
  { ethnicCode: 1076, ethnicType: 'i-Kiribati' } ,
  { ethnicCode: 1077, ethnicType: 'Indian' } ,
  { ethnicCode: 1078, ethnicType: 'Indonesian' } ,
  { ethnicCode: 1079, ethnicType: 'Iranian' } ,
  { ethnicCode: 1080, ethnicType: 'Iraqi' } ,
  { ethnicCode: 1081, ethnicType: 'Irish' } ,
  { ethnicCode: 1082, ethnicType: 'Italian' } ,
  { ethnicCode: 1083, ethnicType: 'Ivorean' } ,
  { ethnicCode: 1084, ethnicType: 'Jamaican' } ,
  { ethnicCode: 1085, ethnicType: 'Japanese' } ,
  { ethnicCode: 1086, ethnicType: 'Javanese' } ,
  { ethnicCode: 1087, ethnicType: 'Jordanian' } ,
  { ethnicCode: 1088, ethnicType: 'Kadazan' } ,
  { ethnicCode: 1089, ethnicType: 'Karen' } ,
  { ethnicCode: 1090, ethnicType: 'Kazakh' } ,
  { ethnicCode: 1091, ethnicType: 'Kenyan' } ,
  { ethnicCode: 1092, ethnicType: 'Khmer' } ,
  { ethnicCode: 1093, ethnicType: 'Korean' } ,
  { ethnicCode: 1094, ethnicType: 'Kurdish' } ,
  { ethnicCode: 1095, ethnicType: 'Kuwaiti' } ,
  { ethnicCode: 1096, ethnicType: 'Lao' } ,
  { ethnicCode: 1097, ethnicType: 'Latvian' } ,
  { ethnicCode: 1098, ethnicType: 'Lebanese' } ,
  { ethnicCode: 1099, ethnicType: 'Liberian' } ,
  { ethnicCode: 1100, ethnicType: 'Libyan' } ,
  { ethnicCode: 1101, ethnicType: 'Lithuanian' } ,
  { ethnicCode: 1102, ethnicType: 'Luxembourg' } ,
  { ethnicCode: 1103, ethnicType: 'Macedonian' } ,
  { ethnicCode: 1104, ethnicType: 'Madurese' } ,
  { ethnicCode: 1105, ethnicType: 'Malawian' } ,
  { ethnicCode: 1106, ethnicType: 'Malay' } ,
  { ethnicCode: 1107, ethnicType: 'Malayali' } ,
  { ethnicCode: 1108, ethnicType: 'Maldivian' } ,
  { ethnicCode: 1109, ethnicType: 'Maltese' } ,
  { ethnicCode: 1110, ethnicType: 'Manx' } ,
  { ethnicCode: 1111, ethnicType: 'Maori' } ,
  { ethnicCode: 1112, ethnicType: 'Masai' } ,
  { ethnicCode: 1113, ethnicType: 'Mauritian' } ,
  { ethnicCode: 1114, ethnicType: 'Mayan' } ,
  { ethnicCode: 1115, ethnicType: 'Mexican' } ,
  { ethnicCode: 1116, ethnicType: 'Moldovan' } ,
  { ethnicCode: 1117, ethnicType: 'Mon' } ,
  { ethnicCode: 1118, ethnicType: 'Mongolian' } ,
  { ethnicCode: 1119, ethnicType: 'Montenegrin' } ,
  { ethnicCode: 1120, ethnicType: 'Moroccan' } ,
  { ethnicCode: 1121, ethnicType: 'Mozambican' } ,
  { ethnicCode: 1122, ethnicType: 'Nauruan' } ,
  { ethnicCode: 1123, ethnicType: 'Nepalese' } ,
  { ethnicCode: 1124, ethnicType: 'New Caledonian' } ,
  { ethnicCode: 1125, ethnicType: 'New Zealander' } ,
  { ethnicCode: 1126, ethnicType: 'Nicaraguan' } ,
  { ethnicCode: 1127, ethnicType: 'Nigerian' } ,
  { ethnicCode: 1128, ethnicType: 'Niuean' } ,
  { ethnicCode: 1129, ethnicType: 'Ni-Vanuatu' } ,
  { ethnicCode: 1130, ethnicType: 'North American Indian' } ,
  { ethnicCode: 1131, ethnicType: 'Norwegian' } ,
  { ethnicCode: 1132, ethnicType: 'Nuer' } ,
  { ethnicCode: 1133, ethnicType: 'Oromo' } ,
  { ethnicCode: 1134, ethnicType: 'Pakistani' } ,
  { ethnicCode: 1135, ethnicType: 'Palestinian' } ,
  { ethnicCode: 1136, ethnicType: 'Papua New Guinean' } ,
  { ethnicCode: 1137, ethnicType: 'Paraguayan' } ,
  { ethnicCode: 1138, ethnicType: 'Pathan' } ,
  { ethnicCode: 1139, ethnicType: 'Peruvian' } ,
  { ethnicCode: 1140, ethnicType: 'Polish' } ,
  { ethnicCode: 1141, ethnicType: 'Portuguese' } ,
  { ethnicCode: 1142, ethnicType: 'Puerto Rican' } ,
  { ethnicCode: 1143, ethnicType: 'Punjabi' } ,
  { ethnicCode: 1144, ethnicType: 'Roma/Gypsy' } ,
  { ethnicCode: 1145, ethnicType: 'Romanian' } ,
  { ethnicCode: 1146, ethnicType: 'Russian' } ,
  { ethnicCode: 1147, ethnicType: 'Salvadoran' } ,
  { ethnicCode: 1148, ethnicType: 'Samoan' } ,
  { ethnicCode: 1149, ethnicType: 'Saudi Arabian' } ,
  { ethnicCode: 1150, ethnicType: 'Scottish' } ,
  { ethnicCode: 1151, ethnicType: 'Serbian' } ,
  { ethnicCode: 1152, ethnicType: 'Seychellois' } ,
  { ethnicCode: 1153, ethnicType: 'Sierra Leonean' } ,
  { ethnicCode: 1154, ethnicType: 'Sikh' } ,
  { ethnicCode: 1155, ethnicType: 'Singaporean' } ,
  { ethnicCode: 1156, ethnicType: 'Sinhalese' } ,
  { ethnicCode: 1157, ethnicType: 'Slovak' } ,
  { ethnicCode: 1158, ethnicType: 'Slovene' } ,
  { ethnicCode: 1159, ethnicType: 'Solomon Islander' } ,
  { ethnicCode: 1160, ethnicType: 'Somali' } ,
  { ethnicCode: 1161, ethnicType: 'Sorb/Wend' } ,
  { ethnicCode: 1162, ethnicType: 'South African' } ,
  { ethnicCode: 1163, ethnicType: 'Spanish' } ,
  { ethnicCode: 1164, ethnicType: 'Sudanese' } ,
  { ethnicCode: 1165, ethnicType: 'Sundanese' } ,
  { ethnicCode: 1166, ethnicType: 'Swedish' } ,
  { ethnicCode: 1167, ethnicType: 'Swiss' } ,
  { ethnicCode: 1168, ethnicType: 'Syrian' } ,
  { ethnicCode: 1169, ethnicType: 'Tahitian' } ,
  { ethnicCode: 1170, ethnicType: 'Taiwanese' } ,
  { ethnicCode: 1171, ethnicType: 'Tajik' } ,
  { ethnicCode: 1172, ethnicType: 'Tamil' } ,
  { ethnicCode: 1173, ethnicType: 'Tanzanian' } ,
  { ethnicCode: 1174, ethnicType: 'Tatar' } ,
  { ethnicCode: 1175, ethnicType: 'Temoq' } ,
  { ethnicCode: 1176, ethnicType: 'Thai' } ,
  { ethnicCode: 1177, ethnicType: 'Tibetan' } ,
  { ethnicCode: 1178, ethnicType: 'Tigrayan' } ,
  { ethnicCode: 1179, ethnicType: 'Tigre' } ,
  { ethnicCode: 1180, ethnicType: 'Timorese' } ,
  { ethnicCode: 1181, ethnicType: 'Tokelauan' } ,
  { ethnicCode: 1182, ethnicType: 'Tongan' } ,
  { ethnicCode: 1183, ethnicType: 'Trinidadian' } ,
  { ethnicCode: 1184, ethnicType: 'Tunisian' } ,
  { ethnicCode: 1185, ethnicType: 'Turkish' } ,
  { ethnicCode: 1186, ethnicType: 'Turkmen' } ,
  { ethnicCode: 1187, ethnicType: 'Tuvaluan' } ,
  { ethnicCode: 1188, ethnicType: 'Ugandan' } ,
  { ethnicCode: 1189, ethnicType: 'Uighur' } ,
  { ethnicCode: 1190, ethnicType: 'Ukrainian' } ,
  { ethnicCode: 1191, ethnicType: 'Uruguayan' } ,
  { ethnicCode: 1192, ethnicType: 'Uzbek' } ,
  { ethnicCode: 1193, ethnicType: 'Venezuelan' } ,
  { ethnicCode: 1194, ethnicType: 'Vietnamese' } ,
  { ethnicCode: 1195, ethnicType: 'Vlach' } ,
  { ethnicCode: 1196, ethnicType: 'Welsh' } ,
  { ethnicCode: 1197, ethnicType: 'Yemeni' } ,
  { ethnicCode: 1198, ethnicType: 'Yoruba' } ,
  { ethnicCode: 1199, ethnicType: 'Zambian' } ,
  { ethnicCode: 1200, ethnicType: 'Zimbabwean' } ,
  { ethnicCode: 1201, ethnicType: 'Zulu' } ,
  { ethnicCode: 1202, ethnicType: 'Albanian' } ,
  { ethnicCode: 1203, ethnicType: 'Algerian' } ,
  { ethnicCode: 1204, ethnicType: 'Israeli' } ,
  { ethnicCode: 1205, ethnicType: 'South Sea Islander' } ,
  { ethnicCode: 1206, ethnicType: 'Grenadian' } ,
  { ethnicCode: 1207, ethnicType: 'Bahaman' } ,
  { ethnicCode: 1208, ethnicType: 'Haitian' } ,
  { ethnicCode: 4115, ethnicType: 'Yemeni' } ,
  { ethnicCode: 4116, ethnicType: 'Bahraini' } ,
  { ethnicCode: 4117, ethnicType: 'Emirati' } ,
  { ethnicCode: 4118, ethnicType: 'Omani' } ,
  { ethnicCode: 4121, ethnicType: 'Bahraini' } ,
  { ethnicCode: 4302, ethnicType: 'Darfurian' } ,
  { ethnicCode: 4305, ethnicType: 'South Sudanese' } ,
  { ethnicCode: 5104, ethnicType: 'Cambodian' } ,
  { ethnicCode: 5205, ethnicType: 'Malaysian' } ,
  { ethnicCode: 7102, ethnicType: 'Bangladeshi' } ,
  { ethnicCode: 7106, ethnicType: 'Fijian Indian' } ,
  { ethnicCode: 7115, ethnicType: 'Sri Lankan' } ,
  { ethnicCode: 7121, ethnicType: 'Bhutanese' } ,
  { ethnicCode: 7123, ethnicType: 'Kashmiri' } ,
  { ethnicCode: 7124, ethnicType: 'Parsi' } ,
  { ethnicCode: 7125, ethnicType: 'Sindhi' } ,
  { ethnicCode: 7127, ethnicType: 'Sri Lankan Tamil' } ,
  { ethnicCode: 7128, ethnicType: 'Indian Tamil' } ,
  { ethnicCode: 7215, ethnicType: 'Kyrgyz' } ,
  { ethnicCode: 8303, ethnicType: 'El Salvadoran' } ,
  { ethnicCode: 9112, ethnicType: 'Cameroonian' } ,
  { ethnicCode: 9113, ethnicType: 'Congolese' } ,
  { ethnicCode: 9118, ethnicType: 'Senegales' } ,
  { ethnicCode: 9211, ethnicType: 'Namibian' } ,
  { ethnicCode: 9233, ethnicType: 'Burundian' } ,
  { ethnicCode: 9237, ethnicType: 'Rwandan' } ,
  { ethnicCode: 9241, ethnicType: 'Swahili' } ,
  { ethnicCode: 9242, ethnicType: 'Swazilander' } ,
  { ethnicCode: 9299, ethnicType: 'Malagasy' } ,
  { ethnicCode: 9999, ethnicType: 'Not provided' }
]